### ISSUE TITLE
Erro com redis

### ISSUE THREAD

**Issue by daniloitj** [sourcelair-blueprints/django-channels-chat#1]
Error 8 connecting to redis:6379. nodename nor servname provided, or not known.

**Comment by akalipetis** [comment]
Hey, have you used our Blueprint? If yes, can you make sure that Redis is correctly connected by going to your [project settings](https://help.sourcelair.com/projects/accessing-your-projects-settings/) and seeing if the Redis connection is there?

If you have not used your Blueprint, I'm afraid I can't be of big help as this highly depends on your configuration.

**Comment by Dean-Christian-Armada** [comment]
Go to settings.py and change this line:

```
 'hosts': [('redis', 6379), ],
```

to:

```
   'hosts': [('127.0.0.1', 6379), ],
```

**Comment by akalipetis** [comment]
This template is used in conjunction with our Blueprint, as can be found here: https://www.sourcelair.com/blog/articles/115/django-channels-chat

The proposed solution is for working locally, but will also require having Redis running which is out of the scope of this tutorial. I'll move on and close this.
