### ISSUE TITLE
Chat does not appear

### ISSUE THREAD

**Issue by HopHouse** [sourcelair-blueprints/django-channels-chat#2]
I am on the final branch, I launch the server with `./manage.py runserver` and I have launched before a redis server with the command `redis-server`.

When I launched firefox with the url 127.0.0.1:8000,  a javascript alert ask for name, I enter it and I arrive on the chat page with my chat on the left but there is just the square, nothing into.

Same thing when I tried to add a person to the chat. 

![capture du 2016-10-11 17-06-13](https://cloud.githubusercontent.com/assets/7113194/19275804/0d03b4b6-8fd5-11e6-900a-e4881bd43b45.png)
![capture du 2016-10-11 17-06-47](https://cloud.githubusercontent.com/assets/7113194/19275830/1e6f561a-8fd5-11e6-8a44-2f635cdf3f22.png)

**Comment by akalipetis** [comment]
Hello @Echel8n - this project has been created to be used inside [SourceLair](https://www.sourcelair.com), following [this tutorial](https://www.sourcelair.com/blog/articles/115/django-channels-chat).

It searches for example for Redis to be available in the `redis` host, so you'll need to change that. I can't think of what else might not work just from a screenshot, sorry.

Also, there's no support provided for other platforms, as there are a number of things that might be misconfigured on your side.
