### ISSUE TITLE
WebSocket Connection Refused

### ISSUE THREAD

**Issue by jzmiller1** [sourcelair-blueprints/django-channels-chat#3]
I'm running on the step/final branch and I'm getting the following in my browser console:

WebSocket connection to 'wss://127.0.0.1/chat/General?username=K' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I'm not really sure what I might need to do to resolve this.  If anyone is watching this repository and has any suggestions that would be awesome.

**Comment by akalipetis** [comment]
You're running this in localhost and you don't have an HTTPS certificate. Is this case, you need to use `ws://` and not `wss://`. This tutorial is meant to be run on [SourceLair](https://www.sourcelair.com) which sports HTTPS for the [public URLs](https://help.sourcelair.com/projects/the-public-url/)
